// <auto-generated />
using System;
using Holonix.Server.Infrastructure.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Holonix.Server.Migrations
{
    [DbContext(typeof(ApplicationDbContext))]
    [Migration("20260328173510_AddEmployeeInviteWorkloads")]
    partial class AddEmployeeInviteWorkloads
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasDefaultSchema("authentication")
                .HasAnnotation("ProductVersion", "8.0.8")
                .HasAnnotation("Relational:MaxIdentifierLength", 128);

            SqlServerModelBuilderExtensions.UseIdentityColumns(modelBuilder);

            modelBuilder.Entity("Holonix.Server.Domain.Entities.ApplicationUser", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)")
                        .HasColumnName("UsersId");

                    b.Property<int>("AccessFailedCount")
                        .HasColumnType("int");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateOnly?>("DateOfBirth")
                        .HasColumnType("date");

                    b.Property<string>("Email")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<bool>("EmailConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("FirstName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("LastName")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("LockoutEnabled")
                        .HasColumnType("bit");

                    b.Property<DateTimeOffset?>("LockoutEnd")
                        .HasColumnType("datetimeoffset");

                    b.Property<string>("NormalizedEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedUserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("PasswordHash")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("PhoneNumber")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("PhoneNumberConfirmed")
                        .HasColumnType("bit");

                    b.Property<string>("ProfileImageBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("SecurityStamp")
                        .HasColumnType("nvarchar(max)");

                    b.Property<bool>("TwoFactorEnabled")
                        .HasColumnType("bit");

                    b.Property<string>("UserName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedEmail")
                        .IsUnique()
                        .HasDatabaseName("EmailIndex")
                        .HasFilter("[NormalizedEmail] IS NOT NULL AND [InactiveDate] IS NULL");

                    b.HasIndex("NormalizedUserName")
                        .IsUnique()
                        .HasDatabaseName("UserNameIndex")
                        .HasFilter("[NormalizedUserName] IS NOT NULL");

                    b.ToTable("Users", "authentication");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Business", b =>
                {
                    b.Property<int>("BusinessId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("BusinessId"));

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsProductBased")
                        .HasColumnType("bit");

                    b.Property<bool>("IsRecurring")
                        .HasColumnType("bit");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<DateOnly>("StartDate")
                        .HasColumnType("date");

                    b.HasKey("BusinessId");

                    b.ToTable("Business", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessDetails", b =>
                {
                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("Address1")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("Address2")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<string>("BusinessIconBase64")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal>("BusinessJobPercentage")
                        .HasColumnType("decimal(5,2)");

                    b.Property<string>("City")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<int?>("CountryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(max)");

                    b.Property<decimal?>("Latitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<decimal?>("Longitude")
                        .HasColumnType("decimal(9,6)");

                    b.Property<string>("State")
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ZipCode")
                        .HasMaxLength(32)
                        .HasColumnType("nvarchar(32)");

                    b.HasKey("BusinessId");

                    b.HasIndex("CountryId");

                    b.ToTable("BusinessDetails", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessRole", b =>
                {
                    b.Property<long>("BusinessRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessRoleId"));

                    b.Property<long>("HierarchyNumber")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("BusinessRoleId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.ToTable("BusinessRole", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessService", b =>
                {
                    b.Property<long>("BusinessServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessServiceId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<int>("ServiceId")
                        .HasColumnType("int");

                    b.HasKey("BusinessServiceId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ServiceId");

                    b.ToTable("BusinessService", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUser", b =>
                {
                    b.Property<long>("BusinessUserId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessUserId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<string>("ReportsToUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("BusinessUserId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("ReportsToUserId");

                    b.HasIndex("UserId");

                    b.ToTable("BusinessUser", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUserAvailability", b =>
                {
                    b.Property<long>("BusinessUserAvailabilityId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessUserAvailabilityId"));

                    b.Property<long>("BusinessUserId")
                        .HasColumnType("bigint");

                    b.Property<byte>("DayOfWeek")
                        .HasColumnType("tinyint");

                    b.Property<DateOnly?>("EffectiveEndDate")
                        .HasColumnType("date");

                    b.Property<DateOnly>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("BusinessUserAvailabilityId");

                    b.HasIndex("BusinessUserId");

                    b.ToTable("BusinessUserAvailability", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUserRole", b =>
                {
                    b.Property<long>("BusinessUserRoleId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessUserRoleId"));

                    b.Property<long>("BusinessRoleId")
                        .HasColumnType("bigint");

                    b.Property<long>("BusinessUserId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("EndDate")
                        .HasColumnType("datetime2");

                    b.Property<DateTime>("StartDate")
                        .HasColumnType("datetime2");

                    b.HasKey("BusinessUserRoleId");

                    b.HasIndex("BusinessRoleId");

                    b.HasIndex("BusinessUserId");

                    b.ToTable("BusinessUserRole", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUserTimeOff", b =>
                {
                    b.Property<long>("BusinessUserTimeOffId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("BusinessUserTimeOffId"));

                    b.Property<long>("BusinessUserId")
                        .HasColumnType("bigint");

                    b.Property<DateOnly?>("EffectiveEndDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EffectiveEndTime")
                        .HasColumnType("time");

                    b.Property<DateOnly?>("EffectiveStartDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly?>("EffectiveStartTime")
                        .HasColumnType("time");

                    b.Property<bool?>("IsAllDay")
                        .HasColumnType("bit");

                    b.HasKey("BusinessUserTimeOffId");

                    b.HasIndex("BusinessUserId");

                    b.ToTable("BusinessUserTimeOff", "business");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Country", b =>
                {
                    b.Property<int>("CountryId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("CountryId"));

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<string>("ThreeLetterIsoCode")
                        .HasMaxLength(3)
                        .HasColumnType("nvarchar(3)");

                    b.Property<string>("TwoLetterIsoCode")
                        .IsRequired()
                        .HasMaxLength(2)
                        .HasColumnType("nvarchar(2)");

                    b.HasKey("CountryId");

                    b.HasIndex("Name")
                        .IsUnique();

                    b.HasIndex("ThreeLetterIsoCode")
                        .IsUnique()
                        .HasFilter("[ThreeLetterIsoCode] IS NOT NULL");

                    b.HasIndex("TwoLetterIsoCode")
                        .IsUnique();

                    b.ToTable("Country", "reference");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Job", b =>
                {
                    b.Property<long>("JobId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<long?>("BusinessUserId")
                        .HasColumnType("bigint");

                    b.Property<decimal>("Cost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("EndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<bool>("IsContract")
                        .HasColumnType("bit");

                    b.Property<long?>("JobRecurrenceId")
                        .HasColumnType("bigint");

                    b.Property<string>("Name")
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.Property<decimal>("NetCost")
                        .HasColumnType("decimal(18,2)");

                    b.Property<DateTime>("StartDateTime")
                        .HasColumnType("datetime2");

                    b.Property<string>("UserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("JobId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("BusinessUserId");

                    b.HasIndex("JobRecurrenceId");

                    b.HasIndex("UserId");

                    b.ToTable("Job", "job");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.JobRecurrence", b =>
                {
                    b.Property<long>("JobRecurrenceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobRecurrenceId"));

                    b.Property<DateOnly?>("EndEffectiveDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("EndTime")
                        .HasColumnType("time");

                    b.Property<byte>("FrequencyId")
                        .HasColumnType("tinyint");

                    b.Property<int>("Interval")
                        .HasColumnType("int");

                    b.Property<bool>("IsActive")
                        .HasColumnType("bit");

                    b.Property<DateOnly>("StartEffectiveDate")
                        .HasColumnType("date");

                    b.Property<TimeOnly>("StartTime")
                        .HasColumnType("time");

                    b.HasKey("JobRecurrenceId");

                    b.ToTable("JobRecurrence", "job");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.JobRecurrenceException", b =>
                {
                    b.Property<long>("JobRecurrenceExceptionId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobRecurrenceExceptionId"));

                    b.Property<DateOnly>("ExceptionDate")
                        .HasColumnType("date");

                    b.Property<long>("JobRecurrenceId")
                        .HasColumnType("bigint");

                    b.Property<DateTime?>("OverrideEndDateTime")
                        .HasColumnType("datetime2");

                    b.Property<DateTime?>("OverrideStartDateTime")
                        .HasColumnType("datetime2");

                    b.HasKey("JobRecurrenceExceptionId");

                    b.HasIndex("JobRecurrenceId");

                    b.ToTable("JobRecurrenceException", "job");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.JobWorkload", b =>
                {
                    b.Property<long>("JobWorkloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("JobWorkloadId"));

                    b.Property<long>("JobId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkloadId")
                        .HasColumnType("bigint");

                    b.HasKey("JobWorkloadId");

                    b.HasIndex("JobId");

                    b.HasIndex("WorkloadId");

                    b.ToTable("JobWorkload", "job");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Service", b =>
                {
                    b.Property<int>("ServiceId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("ServiceId"));

                    b.Property<DateTime?>("InactiveDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("nvarchar(200)");

                    b.HasKey("ServiceId");

                    b.ToTable("Service", "service");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Workload", b =>
                {
                    b.Property<long>("WorkloadId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkloadId"));

                    b.Property<int>("BusinessId")
                        .HasColumnType("int");

                    b.Property<string>("CreatedByUserId")
                        .IsRequired()
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<DateTime>("CreatedDate")
                        .HasColumnType("datetime2");

                    b.Property<string>("NormalizedTargetEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetEmail")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("TargetUserId")
                        .HasMaxLength(450)
                        .HasColumnType("nvarchar(450)");

                    b.Property<long>("WorkloadStatusId")
                        .HasColumnType("bigint");

                    b.Property<long>("WorkloadTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("WorkloadId");

                    b.HasIndex("BusinessId");

                    b.HasIndex("CreatedByUserId");

                    b.HasIndex("NormalizedTargetEmail");

                    b.HasIndex("TargetUserId");

                    b.HasIndex("WorkloadTypeId");

                    b.HasIndex("WorkloadStatusId", "WorkloadTypeId");

                    b.ToTable("Workload", "work");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.WorkloadStatus", b =>
                {
                    b.Property<long>("WorkloadStatusId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkloadStatusId"));

                    b.Property<string>("Status")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.Property<long>("WorkloadTypeId")
                        .HasColumnType("bigint");

                    b.HasKey("WorkloadStatusId");

                    b.HasIndex("WorkloadStatusId", "WorkloadTypeId")
                        .IsUnique();

                    b.HasIndex("WorkloadTypeId", "Status")
                        .IsUnique();

                    b.ToTable("WorkloadStatus", "work");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.WorkloadType", b =>
                {
                    b.Property<long>("WorkloadTypeId")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("bigint");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<long>("WorkloadTypeId"));

                    b.Property<string>("Type")
                        .IsRequired()
                        .HasMaxLength(120)
                        .HasColumnType("nvarchar(120)");

                    b.HasKey("WorkloadTypeId");

                    b.HasIndex("Type")
                        .IsUnique();

                    b.ToTable("WorkloadType", "work");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRole", b =>
                {
                    b.Property<string>("Id")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ConcurrencyStamp")
                        .IsConcurrencyToken()
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("Name")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.Property<string>("NormalizedName")
                        .HasMaxLength(256)
                        .HasColumnType("nvarchar(256)");

                    b.HasKey("Id");

                    b.HasIndex("NormalizedName")
                        .IsUnique()
                        .HasDatabaseName("RoleNameIndex")
                        .HasFilter("[NormalizedName] IS NOT NULL");

                    b.ToTable("Roles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("RoleId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("RoleId");

                    b.ToTable("RoleClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int");

                    SqlServerPropertyBuilderExtensions.UseIdentityColumn(b.Property<int>("Id"));

                    b.Property<string>("ClaimType")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("ClaimValue")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("Id");

                    b.HasIndex("UserId");

                    b.ToTable("UserClaims", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderKey")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("ProviderDisplayName")
                        .HasColumnType("nvarchar(max)");

                    b.Property<string>("UserId")
                        .IsRequired()
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("LoginProvider", "ProviderKey");

                    b.HasIndex("UserId");

                    b.ToTable("UserLogins", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("RoleId")
                        .HasColumnType("nvarchar(450)");

                    b.HasKey("UserId", "RoleId");

                    b.HasIndex("RoleId");

                    b.ToTable("UserRoles", "authentication");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.Property<string>("UserId")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("LoginProvider")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Name")
                        .HasColumnType("nvarchar(450)");

                    b.Property<string>("Value")
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("UserId", "LoginProvider", "Name");

                    b.ToTable("UserTokens", "authentication");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessDetails", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.Business", "Business")
                        .WithOne("Details")
                        .HasForeignKey("Holonix.Server.Domain.Entities.BusinessDetails", "BusinessId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.Country", "Country")
                        .WithMany()
                        .HasForeignKey("CountryId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Business");

                    b.Navigation("Country");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessService", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.Service", "Service")
                        .WithMany()
                        .HasForeignKey("ServiceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("Service");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUser", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", "ReportsToUser")
                        .WithMany()
                        .HasForeignKey("ReportsToUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("ReportsToUser");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUserAvailability", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.BusinessUser", "BusinessUser")
                        .WithMany()
                        .HasForeignKey("BusinessUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUser");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUserRole", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.BusinessRole", "BusinessRole")
                        .WithMany()
                        .HasForeignKey("BusinessRoleId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.BusinessUser", "BusinessUser")
                        .WithMany()
                        .HasForeignKey("BusinessUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessRole");

                    b.Navigation("BusinessUser");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.BusinessUserTimeOff", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.BusinessUser", "BusinessUser")
                        .WithMany()
                        .HasForeignKey("BusinessUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("BusinessUser");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Job", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.BusinessUser", "BusinessUser")
                        .WithMany()
                        .HasForeignKey("BusinessUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Holonix.Server.Domain.Entities.JobRecurrence", "JobRecurrence")
                        .WithMany()
                        .HasForeignKey("JobRecurrenceId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", "User")
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.Navigation("Business");

                    b.Navigation("BusinessUser");

                    b.Navigation("JobRecurrence");

                    b.Navigation("User");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.JobRecurrenceException", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.JobRecurrence", "JobRecurrence")
                        .WithMany()
                        .HasForeignKey("JobRecurrenceId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("JobRecurrence");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.JobWorkload", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.Job", "Job")
                        .WithMany()
                        .HasForeignKey("JobId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.Workload", "Workload")
                        .WithMany()
                        .HasForeignKey("WorkloadId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Job");

                    b.Navigation("Workload");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Workload", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.Business", "Business")
                        .WithMany()
                        .HasForeignKey("BusinessId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", "CreatedByUser")
                        .WithMany()
                        .HasForeignKey("CreatedByUserId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", "TargetUser")
                        .WithMany()
                        .HasForeignKey("TargetUserId")
                        .OnDelete(DeleteBehavior.Restrict);

                    b.HasOne("Holonix.Server.Domain.Entities.WorkloadType", "WorkloadType")
                        .WithMany()
                        .HasForeignKey("WorkloadTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.WorkloadStatus", "WorkloadStatus")
                        .WithMany()
                        .HasForeignKey("WorkloadStatusId", "WorkloadTypeId")
                        .HasPrincipalKey("WorkloadStatusId", "WorkloadTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("Business");

                    b.Navigation("CreatedByUser");

                    b.Navigation("TargetUser");

                    b.Navigation("WorkloadStatus");

                    b.Navigation("WorkloadType");
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.WorkloadStatus", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.WorkloadType", "WorkloadType")
                        .WithMany()
                        .HasForeignKey("WorkloadTypeId")
                        .OnDelete(DeleteBehavior.Restrict)
                        .IsRequired();

                    b.Navigation("WorkloadType");
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityRoleClaim<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserClaim<string>", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserLogin<string>", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserRole<string>", b =>
                {
                    b.HasOne("Microsoft.AspNetCore.Identity.IdentityRole", null)
                        .WithMany()
                        .HasForeignKey("RoleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Microsoft.AspNetCore.Identity.IdentityUserToken<string>", b =>
                {
                    b.HasOne("Holonix.Server.Domain.Entities.ApplicationUser", null)
                        .WithMany()
                        .HasForeignKey("UserId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("Holonix.Server.Domain.Entities.Business", b =>
                {
                    b.Navigation("Details");
                });
#pragma warning restore 612, 618
        }
    }
}
